# Generated by Django 2.1.4 on 2019-05-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticlesApp', '0004_article_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to='images/'),
        ),
    ]
