# Generated by Django 2.1.4 on 2019-05-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Date_Of_Birth',
        ),
    ]
