# Generated by Django 2.1.4 on 2019-05-27 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190528_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
