# Generated by Django 2.1.4 on 2019-05-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190528_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linker',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
