# Generated by Django 2.1.4 on 2019-05-28 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_linker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Username',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
