# Generated by Django 2.1.4 on 2019-05-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='Email_Address',
        ),
    ]
