# Generated by Django 2.1.4 on 2019-05-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190528_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_Pic',
            field=models.ImageField(blank=True, default='ProfilePics/default.jpg', null=True, upload_to='ProfilePics/'),
        ),
    ]
